server:
  port: 8080
  servlet:
    context-path: /api
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/yz1?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 5000

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

jwt:
  secret: TLgWVGpiE2TeWBYQBfN2A7qYyoyRRGdL
  expiration: 86400000